imports:
    - { resource: easyadmin/ }

easy_admin:
    list:
        batch_actions: ['delete']
        actions:
            - name: 'new'
              icon: 'plus-circle'
              label: false
            - name: 'edit'
              icon: 'edit'
              label: false
            - name: 'delete'
              icon: 'trash'
              label: false
    user:
        name_property_path: fullName
    design:
        menu:
            - label: 'Mon activité bancaire'
              icons: 'info-circle'
              children:
                  - entity: 'BankAccount'
                    label: 'Mes comptes bancaires'
                    icon: 'money-check-alt'
            - label: 'Configuration'
              icon: 'cogs'
              children:
                  - entity: 'Bank'
                    label: 'Gestion des banques'
                    icon: 'piggy-bank'
                  - entity: 'ModePayment'
                    label: 'Gestion moyens de paiements'
                    icon: 'wallet'
    site_name: 'Ma gestion bancaire'
    formats:
        number: '%0.2f'
        datetime: 'd/m/Y H:i'
