easy_admin:
    entities:
        ModePayment:
            class: App\Entity\ModePayment
            templates:
                edit: 'admin/ModePayment/edit.html.twig'
                new: 'admin/ModePayment/new.html.twig'
            list:
                title: 'Liste des moyens de paiement'
                fields:
                    - property: name
                      label: 'Nom'
                    - property: updatedBy.fullName
                      label: 'Mis à jour par'
                    - property: updatedAt
                      label: 'Mis à jour le'
            form:
                fields:
                    - property: name
                      label: 'Nom du moyen de paiement'
                      type: 'text'
                      type_options:
                          required: false
